DELIMITER $$

CREATE PROCEDURE ListAllTextbooksByTitle(title VARCHAR(45))
BEGIN
	SELECT T.TEXTBOOK_TITLE, T.TEXTBOOK_EDITION, A.AUTHOR_INITIALS, A.AUTHOR_L_NAME, T.TEXTBOOK_ISBN, T.TEXTBOOK_PRICE, T.TEXTBOOK_COMMENTS, I.IMAGE_FILE, U.FIRST_NAME, U.LAST_NAME, U.CONTACT_NUM, U.EMAIL
	FROM mydb.AUTHOR A, mydb.IMAGE I, mydb.TEXTBOOK T, mydb.textbook_author T_A, mydb.USER U
	WHERE T.TEXTBOOK_TITLE = title
	AND T.TEXTBOOK_ID = T_A.TEXTBOOK_ID
	AND T_A.AUTHOR_ID = A.AUTHOR_ID
	AND I.TEXTBOOK_ID = T.TEXTBOOK_ID
	AND T.USER_ID = U.USER_ID;
END