SELECT T.TEXTBOOK_TITLE, T.TEXTBOOK_EDITION, T.TEXTBOOK_ISBN, T.TEXTBOOK_PRICE, T.TEXTBOOK_COMMENTS, A.AUTHOR_INITIALS, A.AUTHOR_L_NAME, U.FIRST_NAME, U.LAST_NAME, U.CONTACT_NUM, U.EMAIL
FROM mydb.textbook T, mydb.TEXTBOOK_AUTHOR T_A, mydb.AUTHOR A, mydb.USER U
WHERE T.TEXTBOOK_ID = T_A.TEXTBOOK_ID
AND T_A.AUTHOR_ID = A.AUTHOR_ID
AND T.USER_ID = U.USER_ID;
